name: tunes
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/fonts/
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/icons/
    - assets/icons/svg/
    - assets/icons/png/
    - assets/localizations/
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/comfortaa/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/comfortaa/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/comfortaa/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/comfortaa/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/comfortaa/Comfortaa-Bold.ttf
          weight: 700
